### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/docker-image-portus#19]
Since i am not longer using portus myself, i am looking for a maintainer.

I propose @zaggash - he has proved more then enough knowledge, involvement and effort.

Any thoughts?

**Comment by zaggash** [comment]
I'm ok with it. 
I'll try to do my best since I'm using it in my company. 
I have to quick change if something if failling. 
Thx for your  trust.

**Comment by EugenMayer** [comment]
Great! Having those quick changes means, you break stuff easily, but also you fix those fast - so thats how i did those things to!

Lets have this one rule as the onlye one, the tag 2.4-rc11 should be kept intact, since it is used in the rancher-catalog and working over there. I suppose you wont support the rancher catalog?
https://github.com/EugenMayer/docker-rancher-extra-catalogs/tree/master/templates/registry-slim/19

If you plan so, you can surely at some point delete this tag.

Other then that, hub.images are build on very tag, ending up being the same tag on hub. In addition, latest is build whenever you do changes on master.

That said, feel free to change things - i would love if you keep the image general purpose - if any possible. You do not need to do any pull requests any longer, just be bold, do you stuff!

hub.images: if you give me your hub name, i will add you as a contributor to https://hub.docker.com/r/eugenmayer/portus so you can manage stuff as you like.

If you have any questions, just hit me :)

**Comment by EugenMayer** [comment]
@zaggash if you read this, just close this issue and that's it, nothing for me here to track. Thanks!

**Comment by zaggash** [comment]
My dockerhub name is the same as github

**Comment by EugenMayer** [comment]
done :)
