### ISSUE TITLE
Cannot get webhook events working

### ISSUE THREAD

**Issue by andrewsav-datacom** [EugenMayer/docker-image-portus#20]
Hello Eugen, I'm experiencing the issues described here: https://github.com/SUSE/Portus/issues/905 It looks like this should be fixed (the issues is closed), but I'm still seeing these. I'm using your build in rancher with

    image: registry:2.6.0
    image: eugenmayer/portus:2.4-rc11

What might I be doing wrong?

**Comment by EugenMayer** [comment]
Since I am no longer using portus for a longer time now, I cannot give you any advice here. Webhooks have been a pain since, beside that, also garbage collection is a huge issue.

I would suggest using sonar Nexus, see my rancher repo, it's better in any way, but a little bit more configuration effort for namespaced access .. but it has a great GC and a lot more.

Beside that, maybe try to build this image for you, see readme, so building on top of the latest codebase this way. Maybe the bug has been fixed?

Sorry for not being a better help here

**Comment by AndrewSav** [comment]
@EugenMayer No, it's actually a great help. I've been looking for self-hosted registry option for a week now, tried konradkleine/docker-registry-frontend, destelli/europa and now portus and so far not getting any joy. The two former do not have any garbage collection at all which is obviously a problem. I did not know that portus has the same issue, so this is was very valuable to learn.  When you say sonar, do you mean [Sonatype](https://www.sonatype.com/nexus-repository-oss) or something else? I was not able from their site tell the difference between the oss and pro version do you happen to know? Or are you talking about a different product altogether? Thank you very much, your time is really appreciated.

**Comment by EugenMayer** [comment]
@AndrewSav the OSS solution is perfect, there is no downside beside you do not have any official support queue - but thats obvious, isnt it?

Yes its sonatype https://github.com/EugenMayer/docker-rancher-extra-catalogs/tree/master/templates/sona-nexus

I replaced portus with it, artifactor, gemserver and our npm server. So beside its huge for docker images, its even for more, far more.

**Comment by AndrewSav** [comment]
Very cool. Portus [trying to](https://github.com/SUSE/Portus/blob/master/config/config.yml#L38) get garbage collection up and running in latest builds though, so I think I'll might try both if I have time.

From features/usability perspective _if_ I don't need other feeds and _if_ portus sorted out grabage collection and webhooks, is there anything else why nexus might be more prefereable?

I need LDAP integration and Portus has that, not sure about nexus.... But I'll give it a go. Thank you again.

**Comment by EugenMayer** [comment]
The ldap integration in sona nexus is far superior ( far! ) - i am using it too.

GC is by far not easy, i do not expect that to be done soon in portus.

Nexus is far cleaner to configure and actually has far less flaws. You can also host _several_ registries in one single sonatype nexus, portus cannot do that ( still ) - you have to run a portus stack for each and so on.

I never looked back after migrating over and i am actually not biased. Used portus for over 6 months before.

**Comment by AndrewSav** [comment]
Cool. This sounds convincing. Killed half a day on protus today, so will proceed with Nexus as the next candidate. Thank you again for all your help.

**Comment by EugenMayer** [comment]
you are welcome!

**Comment by EugenMayer** [comment]
i updated the portus template to state its discontinued so nobody falls into that trap again!

**Comment by AndrewSav** [comment]
@EugenMayer - and just a suggestion, since portus as is does not seem to be working in your rancher repo and you are not using it, may be it make sense removing it from there, it's not likely useful to you or others in the future, but might put someone on a wrong track. If on to use portus today they better off start with the official repo anyway.

**Comment by AndrewSav** [comment]
@EugenMayer lol, thank you!

**Comment by EugenMayer** [comment]
Telepathy! :)

**Comment by EugenMayer** [comment]
I will add the hint with the official repo - but that wont help with the catalog, its way different and far less flexible, you will not able to configure a lot

**Comment by AndrewSav** [comment]
Do you need to keep it on the catalog?

**Comment by EugenMayer** [comment]
I will try to fix the build right now on the latest image, see if it bootstraps, it changed a lot, and if yes, i release a 2.2.0 version - if not, i will remove it alltogether

**Comment by AndrewSav** [comment]
Sorry, this is not completely off-topic, but since you had experience and I have no one else to ask: did you try different modes like cattle/swarm/kubernetis/mesos on rancher and what is your opinion of these?

**Comment by EugenMayer** [comment]
way to offtopic, join the rancher-users.slack.com channel and lets continue there :)

**Comment by AndrewSav** [comment]
fair enough
